use_frameworks!

platform :ios, '8.0'

target 'MyPodModule_Example' do
  pod 'MyPodModule', :path => '../'

  target 'MyPodModule_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
